### ISSUE TITLE
How are answer documents handled?

### ISSUE THREAD

**Issue by pandel** [UziTech/NSF2SQL#21]
Hi!

While testing your app (only exporting to file atm), which is great in general 👍, I noticed that it does not export DocumentIDs. As answer documents rely on them to connect to the main document, I wonder how you are handling this. Are the connections lost or do your reconnect them via newly generated primary keys?

Regards,
Holger

**Comment by UziTech** [comment]
I do not believe the document ids are saved. I created this software when my company was moving away from Lotus Notes about 5 years ago and haven't used it since.

I currently don't have access to Domino Server to test and update this but if you would be willing to create a PR to includes the document ids as a column in the tables I would be happy to review and merge it.

**Comment by pandel** [comment]
Ah! Many thanks for answer, even though the project is a little bit older :-) - I will get VS and try to add changes myself. If it works I'll create a PR as requested.

Regards,
Holger
