### ISSUE TITLE
Is there any capacity to export attached documents/ embedded docs/objects?

### ISSUE THREAD

**Issue by jon-friedman** [UziTech/NSF2SQL#3]

**Comment by UziTech** [comment]
related to #1 

The documents are all loaded into RAM to construct the tables so it would depend on how much RAM you have and how big the documents are.

I have not used this application in a while as we are finally done with the conversion away from Lotus Notes but it could be changed to use temp files instead of RAM. it would just take a bit longer but wouldn't have a limit on the number of documents exported at one time.

The main reason it has to keep all documents in memory is to create the subtables when a document has a multi-value field. I have seen other applications solve this by just using a text field and join the values with "|" or something other than creating a new table for the field but I prefer the subtable.

I welcome any pull requests.

**Comment by UziTech** [comment]
closing as duplicate to #1
